development:
  adapter: sqlite3
  database: db/sp_board_development.sqlite3
  pool: 5
  timeout: 5000
  username: root
  password:

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: somedatabase_dev
  pool: 5
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

test: &test
  adapter: sqlite3
  database: db/sp_board_test.sqlite3
  pool: 5
  timeout: 5000
  username: root
  password: